# Generated by Django 3.2.8 on 2021-10-15 12:02

import django.core.validators
from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('username', models.CharField(error_messages={'unique': 'このユーザ名はすでに使用されています'}, help_text="ユーザー名は4~30文字の英数字と'_'が使用できます", max_length=30, unique=True, validators=[users.models.UsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='Username')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
                ('icon', models.FileField(blank=True, null=True, upload_to='user_icons/')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Emailアドレス')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='アカウント作成日')),
                ('is_staff', models.BooleanField(default=False, help_text='管理サイトにログインできるかを指定します。', verbose_name='スタッフ権限')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
